nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

yarnPath: .yarn/releases/yarn-3.1.0.cjs

packageExtensions:
  "@yarn-tool/resolve-package@*":
    dependencies:
      "@types/node": "16"

  "@directus/extensions-sdk@*":
    dependencies:
      "@types/express": "^4"
      "@types/geojson": "7946.0.8"
      "@types/pino": "6.3"
      "axios": "0.24.0"
      "express": "^4.17.1"
      "geojson": "*"
      "knex": "0.95.15"
      "knex-schema-inspector": "1.7.3"
      "pino": "6.13"
      "vue": "3"
      "vue-i18n": "9"
      "vue-router": "4"
      "typescript": "4.5.2"

  directus@*:
    dependencies:
      "@types/express": "^4"
      "@types/geojson": "7946.0.8"
      "@types/pino": "6.3"
      "geojson": "*"
      "vue": "3"
      "vue-i18n": "9"
      "vue-router": "4"
